name: ci

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master, feature/**, fix/**, chore/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci || npm i

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Lint
        run: npx eslint . --ext .ts,.tsx

      - name: Test
        run: npm test --if-present -- --ci
